[package]
name = "momento-test-util"
version = "0.52.1"
edition = "2021"
publish = false

[dependencies]
momento = { path = ".." }
anyhow = "1.0.68"
tokio = { version = "1.25.0", features = ["full"] }
uuid = { version = "1.2.2", features = ["v4"] }
scopeguard = "1.1.0"
once_cell = "1.19.0"
